# Render Build Script for Go Backend
# This file tells Render how to build and run your Go application

build:
  # Install Go dependencies
  - go mod download
  
services:
  - type: web
    name: minify-api
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: DB_ADDRESS
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: API_QUOTA
        value: "10"
      - key: APP_PORT
        value: ":3000"
      - key: DOMAIN
        sync: false
      - key: APP_DOMAIN
        sync: false
